#!/usr/bin/env node
/**
 * Build = copy. There is no bundler here on purpose.
 *
 * Two static pages do not justify a toolchain, and without one the deploy has no
 * step that can fail halfway and leave a broken site: the output is assembled in
 * full, then swapped into place atomically by the deploy script.
 *
 * Each site gets its own directory with `shared/` flattened into its root, so the
 * pages can reference `/tokens.css` and `/logo-landing.png` at absolute paths and
 * nginx can serve each site from its own docroot with no rewriting.
 *
 *   dist/landing/   index.html + shared
 *   dist/status/    index.html + status.css + status.js + shared
 *
 * `npm run build` is the same entry point the Repair Desk uses, so the deploy
 * script on the server needs no per-site special casing.
 */

import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(root, 'dist')

const SITES = ['landing', 'status']

/**
 * Where the status page fetches its data.
 *
 * Once the page is hosted on Netlify it can no longer read its own /api/ — that
 * path lives on the server, behind the tunnel, on a different origin. Injected at
 * build time rather than hardcoded so the same source builds for either host: unset
 * (the server) it stays a same-origin relative path, which is what nginx serves.
 */
const STATUS_API = process.env.STATUS_API_ORIGIN ?? ''

/**
 * Security headers for Netlify, generated per site.
 *
 * The two sites need different policies — only the status page makes a
 * cross-origin request — and Netlify reads `_headers` from the publish directory,
 * so each gets its own. Generated rather than committed for the same reason the
 * Warehouse generates its nginx snippet: a hand-maintained second copy of a CSP
 * drifts, and the one that drifts is the one nobody tests.
 */
function headersFor(site) {
  const connect = site === 'status' && STATUS_API ? `'self' ${STATUS_API}` : "'self'"
  const csp = [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self'",
    "font-src 'self'",
    "img-src 'self' data:",
    `connect-src ${connect}`,
    "frame-ancestors 'none'",
    "base-uri 'none'",
    "object-src 'none'",
    "form-action 'self'",
  ].join('; ')

  return [
    '# GENERATED by scripts/build.mjs — do not edit by hand.',
    '',
    '/*',
    '  X-Frame-Options: DENY',
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
    '  Permissions-Policy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), interest-cohort=()',
    `  Content-Security-Policy: ${csp}`,
    '',
    '# Fingerprinted and immutable; the HTML that points at them must never be cached.',
    '/fonts/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '',
  ].join('\n')
}

rmSync(DIST, { recursive: true, force: true })

for (const site of SITES) {
  const out = join(DIST, site)
  mkdirSync(out, { recursive: true })

  // shared/ first, flattened — tokens.css, base.css, theme.js, fonts/, logos.
  cpSync(join(root, 'shared'), out, { recursive: true })
  // then the site's own files, which may legitimately override a shared one.
  cpSync(join(root, site), out, { recursive: true })
}

// A build stamp the deploy script can point at to confirm which release is live.
// COMMIT_REF is set by the deployer; 'local' when someone runs this by hand, the
// same convention as the Repair Desk's vite config.
const ref = (process.env.COMMIT_REF ?? '').slice(0, 7) || 'local'
for (const site of SITES) {
  writeFileSync(join(DIST, site, 'build.txt'), `${ref}\n`)
  writeFileSync(join(DIST, site, '_headers'), headersFor(site))
}

// Bake the data origin into the status page. A placeholder in the source keeps the
// file readable and lets it run unmodified against the server.
//
// The DETAIL view is deliberately removed from a Netlify build and stays on the
// server. It is gated by Cloudflare Access, which authenticates with a cookie —
// fetching its data from another origin would need credentialed CORS and an
// exact-origin allow header, and every one of those is a way to get the gate
// subtly wrong. On the server it is same-origin with its data and needs none of
// it. The public page links across to it instead.
if (STATUS_API) {
  const f = join(DIST, 'status', 'status.js')
  writeFileSync(f, readFileSync(f, 'utf8').replaceAll('__STATUS_API__', STATUS_API))

  rmSync(join(DIST, 'status', 'detail'), { recursive: true, force: true })

  const idx = join(DIST, 'status', 'index.html')
  writeFileSync(
    idx,
    readFileSync(idx, 'utf8').replace('href="/detail/"', `href="${STATUS_API}/detail/"`),
  )
}

console.log(`build: wrote ${SITES.map((s) => `dist/${s}`).join(', ')} (build ${ref})`)
